name: CI Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android NDK
        uses: android-actions/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install cargo‑ndk
        run: cargo install cargo‑ndk

      - name: Gradle build magisk module zipRelease
        run: |
          chmod +x ./gradlew
          ./gradlew :module:zipRelease

      # 调试：打印目录，确认文件生成位置
      - name: Debug list output dir
        run: ls -la module/build/distributions/release/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Identifier‑Patcher‑module
          path: module/build/distributions/release/*.zip
          if-no-files-found: error
